name: Anarchyon

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Iniciar Tunel Pinggy (TCP)
        run: |
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:25565 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 5
          cat pinggy.log

      - name: Executar Servidor
        run: |
          chmod +x start.sh
          ./start.sh

      - name: Salvar e Enviar Progresso
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add world/
          git commit -m "Auto-save do mapa [skip ci]" || echo "Nenhuma alteração para salvar."
          git push