name: Anarchyon

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Iniciar Tunel Pinggy (TCP)
        run: |
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:25565 tcp@a.pinggy.io > pinggy.log 2>&1 &
          sleep 5
          cat pinggy.log

      - name: Executar Servidor
        run: |
          chmod +x start.sh
          ./start.sh